apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-v1
  namespace: doppelganger
  labels:
    app: example-service-v1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service-v1
      version: v1
  template:
    metadata:
      labels:
        app: example-service-v1
        version: v1
    spec:
      containers:
        - name: example-service
          image: example-service-v1:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10

