apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service-v2
  namespace: doppelganger
  labels:
    app: example-service-v2
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-service-v2
      version: v2
  template:
    metadata:
      labels:
        app: example-service-v2
        version: v2
    spec:
      containers:
        - name: example-service
          image: example-service-v2:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10

