apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-service
  namespace: doppelganger
  labels:
    app: monitor-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-service
      version: v1
  template:
    metadata:
      labels:
        app: monitor-service
        version: v1
    spec:
      containers:
        - name: monitor
          image: monitor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: RUST_LOG
              value: "monitor=debug"
            - name: DATABASE_URL
              value: "postgresql://doppelganger:doppelganger_password@postgres.doppelganger.svc.cluster.local:5432/doppelganger"
            - name: REDIS_URL
              value: "redis://redis.doppelganger.svc.cluster.local:6379"
            - name: KAFKA_BROKERS
              value: "kafka.doppelganger.svc.cluster.local:9092"
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10