apiVersion: v1
kind: Service
metadata:
  name: example-service-v2
  namespace: doppelganger
  labels:
    app: example-service-v2
spec:
  selector:
    app: example-service-v2
    version: v2
  ports:
    - name: http
      port: 80
      targetPort: 3003
      protocol: TCP
  type: ClusterIP

