apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  namespace: doppelganger
  labels:
    app: monitor-service
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: monitor-service